# themes/modern_dark/theme.toml
template = "themes/modern_dark/template.conf"

[meta]
name = "Modern Dark"
version = "1.0"

[static]
# Map local tag 'apps' to global ID 'apps_modern'
apps = "apps_modern"

[slots]
# Empty for now
