###############################################################################
# STATIC COMPONENTS REGISTRY
###############################################################################

[static.apps_modern]
path = "catalog/static/apps/apps_modern.conf"

###############################################################################
# TUNABLE COMPONENTS REGISTRY
###############################################################################
